on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEAMSAPP_CLI_VERSION: "3.0.7"
      BOT_AZURE_APP_SERVICE_RESOURCE_ID: ${{secrets.BOT_AZURE_APP_SERVICE_RESOURCE_ID}}
      BOT_ID: ${{secrets.BOT_ID}}
      TEAMS_APP_ID: ${{secrets.TEAMS_APP_ID}}

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: install cli
        run: |
          npm install @microsoft/teamsapp-cli@${{env.TEAMSAPP_CLI_VERSION}}

      - name: Login Azure by service principal
        run: |
          teamsapp auth login azure --username ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_ID}}  \
          --service-principal true \
          --tenant ${{secrets.AZURE_TENANT_ID}} \
          --password ${{secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }} \
          --interactive false

      - name: Deploy to hosting environment
        run: |
          teamsapp deploy --ignore-env-file true \
          --interactive false

      - name: Create .env file
        run: |
          echo "BOT_ID=${{secrets.BOT_ID}}" >> .env
          echo "TEAMS_APP_ID=${{secrets.TEAMS_APP_ID}}" >> .env

      - name: Package app
        run: |
          teamsapp package --env .env

      - name: upload appPackage
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: appPackage/build/appPackage.zip